-- Edmonton practitioner directory, compiled by Arhm from public web sources.
--
-- Two things are carried through deliberately. `basis` records what each row is actually
-- evidenced by, because the source spreadsheet is explicit that 'Employer affiliation'
-- means someone works at an Islamically-integrated service and does NOT confirm their
-- personal religion. And no description asserts anyone's faith: rows carry profession,
-- specialty, and practice, which is what someone needing help after an incident actually
-- needs. Publishing an inferred religious identity for a named private individual is the
-- exact harm this project exists to avoid.
--
-- Source spreadsheet states: "No row was inferred from a person's name."

alter table support_resources drop constraint if exists support_resources_kind_check;
alter table support_resources add constraint support_resources_kind_check
  check (kind in ('police_non_emergency', 'human_rights', 'victim_services', 'legal_clinic',
                  'community_org', 'crisis_line', 'reporting_body', 'lawyer', 'counselling'));

alter table support_resources add column if not exists basis text;

insert into support_resources
  (name, kind, province, scope, description, url, phone, applies_to, basis)
values
  ('Ahmad Berjak', 'lawyer', 'AB', 'municipal', 'Islamic wills & estates; civil litigation, family, immigration, personal injury, real estate; Berjak Law. Contact info@berjaklaw.ca', 'https://berjaklaw.ca', null, array['assault','other','property_damage'], 'Self-identified + association'),
  ('Khalid Berjak', 'lawyer', 'AB', 'municipal', 'Islamic wills & estates; real estate, personal injury, civil litigation, commercial; Berjak Law', 'https://berjaklaw.ca/islamic-wills-edmonton/', null, array['assault','other','property_damage'], 'Self-identified'),
  ('Shabana Imran', 'lawyer', 'AB', 'municipal', 'Family / matrimonial; immigration; Shabana Imran Law, Manulife Place. Contact info@shabanaimran.ca', null, null, array['other'], 'Association listing'),
  ('Shazia Umer', 'lawyer', 'AB', 'municipal', 'Criminal; family, immigration, wills & estates; Umer Law. Contact sumer@umerlaw.com', 'https://www.umerlaw.com', null, array['assault','intimidation','other','property_damage','threat','vandalism'], 'Association listing'),
  ('Abdul Zia', 'lawyer', 'AB', 'municipal', 'Civil litigation; employment, family, human rights, personal injury, constitutional; Qist Law', 'https://qistlaw.com', null, array['assault','harassment','intimidation','online_hate','other','property_damage','threat'], 'Association listing'),
  ('Jouman El-Asmar', 'lawyer', 'AB', 'municipal', 'Immigration, refugee and humanitarian law; El-Asmar Legal', 'https://www.elasmarlegal.com', null, array['other'], 'Association listing'),
  ('Hosneara Begum Thibodeau', 'lawyer', 'AB', 'municipal', 'Immigration; wills & estates, real estate; Prowse Chowne LLP. Contact hthibodeau@prowsechowne.com', null, null, array['other'], 'Association listing'),
  ('Nore Aldein (Norm) Assiff, K.C.', 'lawyer', 'AB', 'municipal', 'Personal injury; Assiff Law. Contact n.assiff@assifflaw.com', 'https://assifflaw.com', null, array['assault','other','property_damage'], 'Association listing'),
  ('Khalid Assaf', 'lawyer', 'AB', 'municipal', 'Personal injury; Assiff Law Office', 'https://assifflaw.com/legal-team/khalid-assaf/', null, array['assault','other','property_damage'], 'Association listing'),
  ('Enas Amy Smaili', 'lawyer', 'AB', 'municipal', 'Personal injury; Moustarah & Company. Contact amy@moustarah.com', 'https://www.moustarah.com', null, array['assault','other','property_damage'], 'Association listing'),
  ('Imran Qureshi', 'lawyer', 'AB', 'municipal', 'Civil litigation; corporate/commercial, employment; DLA Piper (Canada) LLP', 'https://www.dlapiper.com/en-ca/people/q/qureshi-imran', null, array['assault','harassment','intimidation','other','property_damage'], 'Association listing'),
  ('Ijaz Jiwani', 'lawyer', 'AB', 'municipal', 'Civil litigation; Prowse Barrette LLP. Contact ijiwani@prowsebarrette.com', 'https://prowsebarrette.com', null, array['assault','other','property_damage'], 'Association listing'),
  ('Kareem Elboraee', 'lawyer', 'AB', 'municipal', 'Corporate/commercial, banking & finance, civil litigation, real estate, wills & estates; Prowse Barrette LLP. Contact kelboraee@prowsebarrette.com', 'https://prowsebarrette.com', null, array['assault','other','property_damage'], 'Association listing'),
  ('Muhammed-Ali Yassin', 'lawyer', 'AB', 'municipal', 'Corporate/business, commercial, real estate, wills & estates; Forum Law LLP. Contact yassin@forumlaw.ca', 'https://www.forumlaw.ca', null, array['other'], 'Association listing'),
  ('Mohamed S Denny', 'lawyer', 'AB', 'municipal', 'Corporate/business, banking & finance, commercial, real estate, wills & estates; Minsos Stewart Masson (Partner). Contact mdenny@minsoslawyers.com', 'https://www.minsoslawyers.com', null, array['other'], 'Association listing'),
  ('Nizar Dahrouge', 'lawyer', 'AB', 'municipal', 'Corporate/commercial; real estate; Miller Thomson LLP. Contact ndahrouge@millerthomson.com', null, null, array['other'], 'Association listing'),
  ('Nazrina Umarji', 'lawyer', 'AB', 'municipal', 'Administrative, civil litigation, employment, human rights, public law; College of Physicians & Surgeons of Alberta', null, null, array['assault','harassment','intimidation','online_hate','other','property_damage','threat'], 'Association listing'),
  ('Zaid Sayeed', 'lawyer', 'AB', 'municipal', 'Administrative law / regulatory enforcement; Mutual Fund Dealers Association', null, null, array['other'], 'Association listing'),
  ('Irfan Sabir', 'lawyer', 'AB', 'municipal', 'Aboriginal law; Not specified in listing', null, null, array['other'], 'Association listing'),
  ('Ahmed Jomha', 'lawyer', 'AB', 'municipal', 'Business law; Not found', null, null, array['other'], 'Community board role'),
  ('Janine Dhaibi', 'lawyer', 'AB', 'municipal', 'Commercial and construction litigation; Not found (Edmonton-based)', 'https://nccm.ca/team/janine-dhaibi/', null, array['other'], 'Community board role'),
  ('Canadian Muslim Lawyers Association - Alberta Chapter', 'lawyer', 'AB', 'municipal', 'All practice areas; professional association and referral directory; CMLA / ACAM', 'https://directory.cmla-acam.ca/location/edmonton/', null, array['other'], 'Organization'),
  ('Al Rashid Mosque - Islamic Wills service', 'lawyer', 'AB', 'municipal', 'Islamic wills / estate planning (no individual lawyers named); Al Rashid Mosque', 'https://alrashidmosque.ca/will/', null, array['other'], 'Organization'),
  ('Al Rashid Mosque - Family Services', 'lawyer', 'AB', 'municipal', 'Nikah contracts, Islamic divorce, Islamic wills (religious, not legal representation); Al Rashid Mosque', 'https://alrashidmosque.ca/family-services/', null, array['other'], 'Organization'),
  ('Audrey Kodye', 'counselling', 'AB', 'municipal', 'Registered Psychologist (R.Psych); Islamic psychology; anxiety; Muslim women; Overcome Anxiety Psychological', 'https://overanxietypsych.com', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Self-identified'),
  ('Sadique Pathan', 'counselling', 'AB', 'municipal', 'Registered Social Worker (MSW, RSW); Islamically integrated counselling; trauma, addictions, couples; Revive Counselling', 'https://www.revivecounselling.ca/sadique-pathan', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Self-identified'),
  ('Lubna Zaeem', 'counselling', 'AB', 'municipal', 'Registered Psychologist; Clinical Director; Islamic Psychology, Shifa Technique; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Self-identified'),
  ('Moona Khan', 'counselling', 'AB', 'municipal', 'Registered Social Worker (MSW, RSW); Islamically integrated counselling; CBT, DBT, trauma-informed; Revive Counselling', 'https://www.revivecounselling.ca/moona-khan', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Self-identified'),
  ('Mona Fayad Sabbahi', 'counselling', 'AB', 'municipal', 'Hijama practitioner (not a regulated profession); Prophetic cupping / sunnah medicine; Hijama By Mona. Contact monasabbahi@gmail.com', null, null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Self-identified'),
  ('Mohammed Ayyash', 'counselling', 'AB', 'municipal', 'Counselling Therapist; Clinical Counselling Team Lead; trauma-informed care; English/Arabic; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Abeer Mourad', 'counselling', 'AB', 'municipal', 'Registered Psychologist (PhD); Anxiety, depression, OCD, trauma; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Lule Girma Begashaw', 'counselling', 'AB', 'municipal', 'Registered Psychologist; Trauma, depression, anxiety; refugees and immigrants; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Homa Fatemeh Ebrahimi', 'counselling', 'AB', 'municipal', 'Registered Psychologist; Trauma-informed and transpersonal approaches; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Hazim Al-Faouri', 'counselling', 'AB', 'municipal', 'Canadian Certified Counsellor; Advanced EMDR trauma; English/Arabic; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Sana Atiq-Omar', 'counselling', 'AB', 'municipal', 'Psychotherapist, Canadian Certified Counsellor; Art therapy, CBT, ACT; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Naheed Amjad-Minhas', 'counselling', 'AB', 'municipal', 'Counselling Therapist; Grief recovery; English/Urdu/Punjabi; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Iram Bilal', 'counselling', 'AB', 'municipal', 'Registered Social Worker; Children through geriatric populations; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Asha Osman', 'counselling', 'AB', 'municipal', 'Registered Social Worker; Sensorimotor psychotherapy; trauma, ADHD; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Mahnum Iqbal', 'counselling', 'AB', 'municipal', 'Registered Provisional Psychologist; Anxiety, depression, panic, trauma; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Wessam Abosaid', 'counselling', 'AB', 'municipal', 'Registered Provisional Psychologist; Depression, anxiety, trauma; English/Arabic; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Mona Abouguendia', 'counselling', 'AB', 'municipal', 'Registered Provisional Psychologist; Depression, anxiety, trauma, life transitions; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Nida Mir', 'counselling', 'AB', 'municipal', 'Registered Dietitian; Nutrition counselling; food security; IslamicFamily (IFSSA)', 'https://www.islamicfamily.ca/counselling', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Employer affiliation'),
  ('Dr. Taha Jomha', 'counselling', 'AB', 'municipal', 'Dentist; General dentistry; Summerlea Dental / Jomha Dental, Edmonton', 'http://www.jomhadental.ca', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Community board role'),
  ('Dr. Yaasin Abdulrehman', 'counselling', 'AB', 'municipal', 'Physician - Vascular Surgeon (MD, FRCSC); Vascular surgery; Northern Alberta Vascular Centre', 'https://albertavascular.ca', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Community board role'),
  ('Dr. Salma Kiani', 'counselling', 'AB', 'municipal', 'Optometrist; Optometry; Greater Edmonton Eyecare', 'https://geeyecare.com', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Community board role'),
  ('Sihame Farhat', 'counselling', 'AB', 'municipal', 'Registered Dental Hygienist; Dental hygiene; Not found', null, null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Community board role'),
  ('IslamicFamily (IFSSA)', 'counselling', 'AB', 'municipal', 'Organization; Islamically-integrated counselling, mental health, dietitian, newcomer support; IslamicFamily Hub, 2-786, 10545 108 St, Edmonton, AB T5H 2Z8. Contact counselling@islamicfamily.ca', 'https://www.islamicfamily.ca', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Organization'),
  ('Revive Counselling', 'counselling', 'AB', 'municipal', 'Organization; Islamically Integrated Counselling listed as a named service area; North and South Edmonton locations', 'https://www.revivecounselling.ca', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Organization'),
  ('Overcome Anxiety Psychological', 'counselling', 'AB', 'municipal', 'Organization; Islamic therapy / counselling for Muslim women; anxiety; Edmonton (largely virtual)', 'https://overanxietypsych.com', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Organization'),
  ('Hijama By Mona', 'counselling', 'AB', 'municipal', 'Organization (unregulated practice); Hijama / prophetic cupping; 12814 143A Ave NW, Edmonton, AB T6V 1C8', 'https://www.hijamabymona.ca', null, array['harassment','intimidation','threat','assault','online_hate','other'], 'Organization')
on conflict do nothing;
